### PR TITLE
images are fixed in dashboard

### PR DESCRIPTION
**Pull request by krishan-here**
fixed mention changes in #3 and also some ui fixes in dashboard.

### CODE REVIEW

**Comment by gbowne1** [comment]
Still doesn't work after today's fixes.

Here is my render in Firefox 104 (64 Bit) Linux in Debian 11
Screenshot 2022-09-05 at 13-51-50 Radio Logger

**Comment by gbowne1** [comment]
Hrm ignore that.. Was loading dashboard in VSCodes localhost server.  doesn't work that way.  It does if you npm start
and load localhost in your localhost:3000 browser

**Comment by krishan-here** [comment]
what is VSCodes localserver? are you talking about live server.

**Comment by gbowne1** [comment]
Yes Live Server and the same with a preview extension I have.  

I don't know if you can change Live Server's port to match.

Its set to 5500 / 5501

**Pull request merged**
