### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by TechLateef**

### CODE REVIEW

**Comment by TechLateef** [comment]
check this out

**Review by gbowne1 — APPROVED** [review]
This change looks good as starting work on the API.
Approving.

**Review by gbowne1 — APPROVED** [review]
Looks like this should fix issues with mongo drivers.

**Review by gbowne1 — APPROVED** [review]
I was not sure what to do about all the user and routing stuff or whether we needed a .env

**Comment by gbowne1** [comment]
Will look at this in depth in 8hrs

**Comment by TechLateef** [comment]
we will need the .env but dont worry about that onces the api commence we will handle that

**Comment by TechLateef** [comment]
we we talk on whatsapp or any other platform

**Comment by gbowne1** [comment]
I thought it might need a separate .env outside of the user stuff now in the API. Was not sure.

I would like to leave communications on here.

**Comment by TechLateef** [comment]
okay 

the .env will be in the root

**Comment by TechLateef** [comment]
am not kind of use to it but no p with time i will get use to it 

that's why i  reply late   but its cool

**Comment by gbowne1** [comment]
Its ok. Chances are I will see comments etc quickly unless it is late in the US.   I am on twitter but I hardly ever get time to post more there.

**Pull request merged**
